# yaml file to create a deployment for  a container from docker registry

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cetha-api
  namespace: cetha
  labels:
    app: cetha-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cetha-api
  template:
    metadata:
      labels:
        app: cetha-api
    spec:
      containers:
      - name: cetha-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 3000

        